# Generated by Django 2.0.6 on 2019-07-30 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0002_tcar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcar',
            options={},
        ),
    ]
