# Generated by Django 2.0.6 on 2019-07-30 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_auto_20190730_1033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tcar',
        ),
    ]
